//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Songify_Slim.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Songify_Slim.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist is blocked.
        /// </summary>
        public static string brw_ArtistBlocked {
            get {
                return ResourceManager.GetString("brw_ArtistBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string brw_cmd_description {
            get {
                return ResourceManager.GetString("brw_cmd_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string brw_cmd_enabled {
            get {
                return ResourceManager.GetString("brw_cmd_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the next song in queue.
        /// </summary>
        public static string brw_cmd_next {
            get {
                return ResourceManager.GetString("brw_cmd_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string brw_cmd_off {
            get {
                return ResourceManager.GetString("brw_cmd_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string brw_cmd_on {
            get {
                return ResourceManager.GetString("brw_cmd_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumes or pauses the current playback..
        /// </summary>
        public static string brw_cmd_playpause {
            get {
                return ResourceManager.GetString("brw_cmd_playpause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the queue position of the users songrequests.
        /// </summary>
        public static string brw_cmd_pos {
            get {
                return ResourceManager.GetString("brw_cmd_pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes the latest song request of the user.
        /// </summary>
        public static string brw_cmd_remove {
            get {
                return ResourceManager.GetString("brw_cmd_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skips the current song (Broadcaster / Mod / Requester).
        /// </summary>
        public static string brw_cmd_skip {
            get {
                return ResourceManager.GetString("brw_cmd_skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts a vote to skip the current song.
        /// </summary>
        public static string brw_cmd_skipvote {
            get {
                return ResourceManager.GetString("brw_cmd_skipvote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of votes needed.
        /// </summary>
        public static string brw_cmd_skipvotecount {
            get {
                return ResourceManager.GetString("brw_cmd_skipvotecount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the current song.
        /// </summary>
        public static string brw_cmd_song {
            get {
                return ResourceManager.GetString("brw_cmd_song", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds the current song to the playlist selected in Spotify config.
        /// </summary>
        public static string brw_cmd_songlike {
            get {
                return ResourceManager.GetString("brw_cmd_songlike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger.
        /// </summary>
        public static string brw_cmd_trigger {
            get {
                return ResourceManager.GetString("brw_cmd_trigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error fetching songdata.
        /// </summary>
        public static string brw_FetchError {
            get {
                return ResourceManager.GetString("brw_FetchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure the bot responses for the following scenarios:.
        /// </summary>
        public static string brw_Header {
            get {
                return ResourceManager.GetString("brw_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max songs in queue.
        /// </summary>
        public static string brw_MaxSongs {
            get {
                return ResourceManager.GetString("brw_MaxSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadcaster / Moderator / Requester skipped the song.
        /// </summary>
        public static string brw_ModSkip {
            get {
                return ResourceManager.GetString("brw_ModSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response for !next command.
        /// </summary>
        public static string brw_Next {
            get {
                return ResourceManager.GetString("brw_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No song has been specified (empty request).
        /// </summary>
        public static string brw_NoSong {
            get {
                return ResourceManager.GetString("brw_NoSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response for !pos command.
        /// </summary>
        public static string brw_Pos {
            get {
                return ResourceManager.GetString("brw_Pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text that gets added to the response if points are refunded.
        /// </summary>
        public static string brw_Refund {
            get {
                return ResourceManager.GetString("brw_Refund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response for !song command.
        /// </summary>
        public static string brw_Song {
            get {
                return ResourceManager.GetString("brw_Song", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song already in queue.
        /// </summary>
        public static string brw_SongInQueue {
            get {
                return ResourceManager.GetString("brw_SongInQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response for !songlike command.
        /// </summary>
        public static string brw_SongLike {
            get {
                return ResourceManager.GetString("brw_SongLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song too long.
        /// </summary>
        public static string brw_SongTooLong {
            get {
                return ResourceManager.GetString("brw_SongTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song added successfully.
        /// </summary>
        public static string brw_Success {
            get {
                return ResourceManager.GetString("brw_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        public static string brw_tc_Commands {
            get {
                return ResourceManager.GetString("brw_tc_Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responses.
        /// </summary>
        public static string brw_tc_Responses {
            get {
                return ResourceManager.GetString("brw_tc_Responses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User voted to skip the current song.
        /// </summary>
        public static string brw_VoteSkip {
            get {
                return ResourceManager.GetString("brw_VoteSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string bw_btnAdd {
            get {
                return ResourceManager.GetString("bw_btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string bw_btnClear {
            get {
                return ResourceManager.GetString("bw_btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string bw_cbArtist {
            get {
                return ResourceManager.GetString("bw_cbArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string bw_cbUser {
            get {
                return ResourceManager.GetString("bw_cbUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked Artists.
        /// </summary>
        public static string bw_lblBlockedArtists {
            get {
                return ResourceManager.GetString("bw_lblBlockedArtists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked Users.
        /// </summary>
        public static string bw_lblBlockedUsers {
            get {
                return ResourceManager.GetString("bw_lblBlockedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string bw_menu_Delete {
            get {
                return ResourceManager.GetString("bw_menu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Reward.
        /// </summary>
        public static string crw_CreateReward {
            get {
                return ResourceManager.GetString("crw_CreateReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an issue creating the reward. Make sure you don&apos;t have a reward with the same name already..
        /// </summary>
        public static string crw_CreateRewardError {
            get {
                return ResourceManager.GetString("crw_CreateRewardError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reward &quot;{name}&quot; has been created..
        /// </summary>
        public static string crw_CreateRewardSuccess {
            get {
                return ResourceManager.GetString("crw_CreateRewardSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string crw_RewardCost {
            get {
                return ResourceManager.GetString("crw_RewardCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt.
        /// </summary>
        public static string crw_RewardPrompt {
            get {
                return ResourceManager.GetString("crw_RewardPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string crw_RewardTitle {
            get {
                return ResourceManager.GetString("crw_RewardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string lang_deDE {
            get {
                return ResourceManager.GetString("lang_deDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string lang_en {
            get {
                return ResourceManager.GetString("lang_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string lang_es {
            get {
                return ResourceManager.GetString("lang_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string lang_fr {
            get {
                return ResourceManager.GetString("lang_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string lang_ru {
            get {
                return ResourceManager.GetString("lang_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot Account.
        /// </summary>
        public static string msgbx_BotAccount {
            get {
                return ResourceManager.GetString("msgbx_BotAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string msgbx_No {
            get {
                return ResourceManager.GetString("msgbx_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully linked to {account}. Would you also like to use this account as the chat bot?.
        /// </summary>
        public static string msgbx_UseAsBotAccount {
            get {
                return ResourceManager.GetString("msgbx_UseAsBotAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string msgbx_Yes {
            get {
                return ResourceManager.GetString("msgbx_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please link your Spotify account. Settings -&gt; Spotify.
        /// </summary>
        public static string mw_LiveOutputLinkSpotify {
            get {
                return ResourceManager.GetString("mw_LiveOutputLinkSpotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist - Title.
        /// </summary>
        public static string mw_LiveOutputPlaceholder {
            get {
                return ResourceManager.GetString("mw_LiveOutputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocklist.
        /// </summary>
        public static string mw_menu_Blacklist {
            get {
                return ResourceManager.GetString("mw_menu_Blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Us A Coffee.
        /// </summary>
        public static string mw_menu_BuyUsACoffee {
            get {
                return ResourceManager.GetString("mw_menu_BuyUsACoffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string mw_menu_Connect {
            get {
                return ResourceManager.GetString("mw_menu_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console.
        /// </summary>
        public static string mw_menu_Console {
            get {
                return ResourceManager.GetString("mw_menu_Console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string mw_menu_Disconnect {
            get {
                return ResourceManager.GetString("mw_menu_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string mw_menu_Exit {
            get {
                return ResourceManager.GetString("mw_menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string mw_menu_File {
            get {
                return ResourceManager.GetString("mw_menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string mw_menu_Help {
            get {
                return ResourceManager.GetString("mw_menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string mw_menu_Help_About {
            get {
                return ResourceManager.GetString("mw_menu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log-Folder.
        /// </summary>
        public static string mw_menu_Help_LogFolder {
            get {
                return ResourceManager.GetString("mw_menu_Help_LogFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string mw_menu_History {
            get {
                return ResourceManager.GetString("mw_menu_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History Browser.
        /// </summary>
        public static string mw_menu_History_Browser {
            get {
                return ResourceManager.GetString("mw_menu_History_Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History Window.
        /// </summary>
        public static string mw_menu_History_Window {
            get {
                return ResourceManager.GetString("mw_menu_History_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch notes.
        /// </summary>
        public static string mw_menu_PatchNotes {
            get {
                return ResourceManager.GetString("mw_menu_PatchNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        public static string mw_menu_Queue {
            get {
                return ResourceManager.GetString("mw_menu_Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue Browser.
        /// </summary>
        public static string mw_menu_Queue_Browser {
            get {
                return ResourceManager.GetString("mw_menu_Queue_Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Queue.
        /// </summary>
        public static string mw_menu_Queue_Clear {
            get {
                return ResourceManager.GetString("mw_menu_Queue_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue Window.
        /// </summary>
        public static string mw_menu_Queue_Window {
            get {
                return ResourceManager.GetString("mw_menu_Queue_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string mw_menu_Settings {
            get {
                return ResourceManager.GetString("mw_menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Requests.
        /// </summary>
        public static string mw_menu_SongRequests {
            get {
                return ResourceManager.GetString("mw_menu_SongRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Us.
        /// </summary>
        public static string mw_menu_Support {
            get {
                return ResourceManager.GetString("mw_menu_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot Config.
        /// </summary>
        public static string mw_menu_Twitch_Bot {
            get {
                return ResourceManager.GetString("mw_menu_Twitch_Bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Online Status.
        /// </summary>
        public static string mw_menu_Twitch_CheckOnlineStatus {
            get {
                return ResourceManager.GetString("mw_menu_Twitch_CheckOnlineStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in with Twitch.
        /// </summary>
        public static string mw_menu_Twitch_TwitchLoggedIn {
            get {
                return ResourceManager.GetString("mw_menu_Twitch_TwitchLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with Twitch.
        /// </summary>
        public static string mw_menu_Twitch_TwitchLogin {
            get {
                return ResourceManager.GetString("mw_menu_Twitch_TwitchLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string mw_menu_View {
            get {
                return ResourceManager.GetString("mw_menu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widget.
        /// </summary>
        public static string mw_menu_Widget {
            get {
                return ResourceManager.GetString("mw_menu_Widget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string s_Length {
            get {
                return ResourceManager.GetString("s_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string s_Name {
            get {
                return ResourceManager.GetString("s_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requester.
        /// </summary>
        public static string s_Requester {
            get {
                return ResourceManager.GetString("s_Requester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string s_Save {
            get {
                return ResourceManager.GetString("s_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string s_Time {
            get {
                return ResourceManager.GetString("s_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string s_Upload {
            get {
                return ResourceManager.GetString("s_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon songify {
            get {
                object obj = ResourceManager.GetObject("songify", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color:.
        /// </summary>
        public static string sw_Appearance_Color {
            get {
                return ResourceManager.GetString("sw_Appearance_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Theme.
        /// </summary>
        public static string sw_Appearance_ThemeDark {
            get {
                return ResourceManager.GetString("sw_Appearance_ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Theme.
        /// </summary>
        public static string sw_Appearance_ThemeLight {
            get {
                return ResourceManager.GetString("sw_Appearance_ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPORT CONFIG.
        /// </summary>
        public static string sw_Config_Export {
            get {
                return ResourceManager.GetString("sw_Config_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get beta updates.
        /// </summary>
        public static string sw_Config_GetBetaUpdates {
            get {
                return ResourceManager.GetString("sw_Config_GetBetaUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMPORT CONFIG.
        /// </summary>
        public static string sw_Config_Import {
            get {
                return ResourceManager.GetString("sw_Config_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Config.
        /// </summary>
        public static string sw_Config_ResetConfig {
            get {
                return ResourceManager.GetString("sw_Config_ResetConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autoconnect.
        /// </summary>
        public static string sw_Integration_Autoconnect {
            get {
                return ResourceManager.GetString("sw_Integration_Autoconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LINK.
        /// </summary>
        public static string sw_Integration_btnLink {
            get {
                return ResourceManager.GetString("sw_Integration_btnLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Bot Responses &amp; Commands.
        /// </summary>
        public static string sw_Integration_ConfigureResponses {
            get {
                return ResourceManager.GetString("sw_Integration_ConfigureResponses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Rewards.
        /// </summary>
        public static string Sw_Integration_ManageRewards {
            get {
                return ResourceManager.GetString("Sw_Integration_ManageRewards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max SR / User (based on user level).
        /// </summary>
        public static string Sw_Integration_MaxSrUser {
            get {
                return ResourceManager.GetString("Sw_Integration_MaxSrUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum user level required for SR.
        /// </summary>
        public static string Sw_Integration_MinUserLevel {
            get {
                return ResourceManager.GetString("Sw_Integration_MinUserLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NB Username (Twitch Username).
        /// </summary>
        public static string sw_Integration_NBWatermark {
            get {
                return ResourceManager.GetString("sw_Integration_NBWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit Twitch activity to only work when stream is live (needs Twitch login).
        /// </summary>
        public static string Sw_Integration_OnlyWorkWhenLive {
            get {
                return ResourceManager.GetString("Sw_Integration_OnlyWorkWhenLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to always (make SR free).
        /// </summary>
        public static string Sw_Integration_RefundAlways {
            get {
                return ResourceManager.GetString("Sw_Integration_RefundAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song contains blocked artist(s).
        /// </summary>
        public static string Sw_Integration_RefundArtistBlocked {
            get {
                return ResourceManager.GetString("Sw_Integration_RefundArtistBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to be able to refund points, the reward has to be created through Songify. Select a reward that is manageable or create a new one..
        /// </summary>
        public static string sw_Integration_RefundDisclaimer {
            get {
                return ResourceManager.GetString("sw_Integration_RefundDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No song was found.
        /// </summary>
        public static string Sw_Integration_RefundNoSongFound {
            get {
                return ResourceManager.GetString("Sw_Integration_RefundNoSongFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund when.
        /// </summary>
        public static string Sw_Integration_RefundOn {
            get {
                return ResourceManager.GetString("Sw_Integration_RefundOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song has been added to the queue.
        /// </summary>
        public static string Sw_Integration_RefundSongAdded {
            get {
                return ResourceManager.GetString("Sw_Integration_RefundSongAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song is already in queue.
        /// </summary>
        public static string Sw_Integration_RefundSongAlreadyInQueue {
            get {
                return ResourceManager.GetString("Sw_Integration_RefundSongAlreadyInQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song is not available in region.
        /// </summary>
        public static string Sw_Integration_RefundSongNotAvailable {
            get {
                return ResourceManager.GetString("Sw_Integration_RefundSongNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song duration is too long.
        /// </summary>
        public static string Sw_Integration_RefundSongTooLong {
            get {
                return ResourceManager.GetString("Sw_Integration_RefundSongTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotify is not connected.
        /// </summary>
        public static string Sw_Integration_RefundSpotifyNotConnected {
            get {
                return ResourceManager.GetString("Sw_Integration_RefundSpotifyNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is blocked from SR.
        /// </summary>
        public static string Sw_Integration_RefundUSerBlocked {
            get {
                return ResourceManager.GetString("Sw_Integration_RefundUSerBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User level is too low.
        /// </summary>
        public static string Sw_Integration_RefundUserLevelLow {
            get {
                return ResourceManager.GetString("Sw_Integration_RefundUserLevelLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked account:.
        /// </summary>
        public static string sw_Integration_SpotifyLinked {
            get {
                return ResourceManager.GetString("sw_Integration_SpotifyLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send offline notification to chat.
        /// </summary>
        public static string Sw_Integration_StreamNotLifeNotification {
            get {
                return ResourceManager.GetString("Sw_Integration_StreamNotLifeNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitch account.
        /// </summary>
        public static string sw_Integration_Twitch {
            get {
                return ResourceManager.GetString("sw_Integration_Twitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel to join.
        /// </summary>
        public static string sw_Integration_TwitchChWatermark {
            get {
                return ResourceManager.GetString("sw_Integration_TwitchChWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string Sw_Integtation_Tc_Accounts {
            get {
                return ResourceManager.GetString("Sw_Integtation_Tc_Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewards.
        /// </summary>
        public static string Sw_Integtation_Tc_Rewards {
            get {
                return ResourceManager.GetString("Sw_Integtation_Tc_Rewards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Requests.
        /// </summary>
        public static string Sw_Integtation_Tc_SongRequests {
            get {
                return ResourceManager.GetString("Sw_Integtation_Tc_SongRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically Announce Song To Chat.
        /// </summary>
        public static string Sw_intergration_AutoAnnounce {
            get {
                return ResourceManager.GetString("Sw_intergration_AutoAnnounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward for Song Skip.
        /// </summary>
        public static string sw_Spotify_RewardSkip {
            get {
                return ResourceManager.GetString("sw_Spotify_RewardSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward for Song Requests.
        /// </summary>
        public static string sw_Spotify_RewardSR {
            get {
                return ResourceManager.GetString("sw_Spotify_RewardSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Points Reward ID.
        /// </summary>
        public static string sw_SpotifySR_ChannelPoints {
            get {
                return ResourceManager.GetString("sw_SpotifySR_ChannelPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Queue on Startup.
        /// </summary>
        public static string sw_SpotifySR_ClearQ {
            get {
                return ResourceManager.GetString("sw_SpotifySR_ClearQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Cooldown (seconds).
        /// </summary>
        public static string sw_SpotifySR_CommandCD {
            get {
                return ResourceManager.GetString("sw_SpotifySR_CommandCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max song length (in minutes).
        /// </summary>
        public static string sw_SpotifySR_MaxLength {
            get {
                return ResourceManager.GetString("sw_SpotifySR_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Requests per User.
        /// </summary>
        public static string sw_SpotifySR_MaxReq {
            get {
                return ResourceManager.GetString("sw_SpotifySR_MaxReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Message Logging.
        /// </summary>
        public static string sw_SpotifySR_MessageLogging {
            get {
                return ResourceManager.GetString("sw_SpotifySR_MessageLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable SR (Command).
        /// </summary>
        public static string sw_SpotifySR_SRCommand {
            get {
                return ResourceManager.GetString("sw_SpotifySR_SRCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable SR (Channel Rewards).
        /// </summary>
        public static string sw_SpotifySR_SRReward {
            get {
                return ResourceManager.GetString("sw_SpotifySR_SRReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !ssr command moved to bot config.
        /// </summary>
        public static string sw_SpotifySR_SsrMovedToBotConfig {
            get {
                return ResourceManager.GetString("sw_SpotifySR_SsrMovedToBotConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unlimited song requests.
        /// </summary>
        public static string Sw_SpotifySR_UnlimitedSRs {
            get {
                return ResourceManager.GetString("Sw_SpotifySR_UnlimitedSRs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed user levels for SR command.
        /// </summary>
        public static string sw_SpotifySR_Userlevel_command {
            get {
                return ResourceManager.GetString("sw_SpotifySR_Userlevel_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed user levels for SR reward.
        /// </summary>
        public static string sw_SpotifySR_Userlevel_reward {
            get {
                return ResourceManager.GetString("sw_SpotifySR_Userlevel_reward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open queue window on startup.
        /// </summary>
        public static string Sw_System_OpenQueueOnStartup {
            get {
                return ResourceManager.GetString("Sw_System_OpenQueueOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide account names and profile pictures.
        /// </summary>
        public static string Sw_System_Privacy {
            get {
                return ResourceManager.GetString("Sw_System_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Sw_System_PrivacyHeader {
            get {
                return ResourceManager.GetString("Sw_System_PrivacyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string sw_tc_Appearance {
            get {
                return ResourceManager.GetString("sw_tc_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        public static string sw_tc_Config {
            get {
                return ResourceManager.GetString("sw_tc_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitch.
        /// </summary>
        public static string sw_tc_Integration {
            get {
                return ResourceManager.GetString("sw_tc_Integration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string sw_tc_Output {
            get {
                return ResourceManager.GetString("sw_tc_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add all song requests to the playlist.
        /// </summary>
        public static string sw_tc_Spotify_AddSongsToPlaylist {
            get {
                return ResourceManager.GetString("sw_tc_Spotify_AddSongsToPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string sw_tc_System {
            get {
                return ResourceManager.GetString("sw_tc_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Server.
        /// </summary>
        public static string sw_tc_WebServer {
            get {
                return ResourceManager.GetString("sw_tc_WebServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to append spaces.
        /// </summary>
        public static string sw_tcOutput_AddSpaces {
            get {
                return ResourceManager.GetString("sw_tcOutput_AddSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Directory.
        /// </summary>
        public static string sw_tcOutput_Directory {
            get {
                return ResourceManager.GetString("sw_tcOutput_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download album cover (only works with API).
        /// </summary>
        public static string sw_tcOutput_DownloadAlbum {
            get {
                return ResourceManager.GetString("sw_tcOutput_DownloadAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Format (Text file &amp; Widget).
        /// </summary>
        public static string sw_tcOutput_Format {
            get {
                return ResourceManager.GetString("sw_tcOutput_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Format (Twitch Chat).
        /// </summary>
        public static string sw_tcOutput_Format2 {
            get {
                return ResourceManager.GetString("sw_tcOutput_Format2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Text.
        /// </summary>
        public static string sw_tcOutput_PauseText {
            get {
                return ResourceManager.GetString("sw_tcOutput_PauseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom pause text (blank for emtpy text file).
        /// </summary>
        public static string sw_tcOutput_PauseWatermark {
            get {
                return ResourceManager.GetString("sw_tcOutput_PauseWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Artist and Title.
        /// </summary>
        public static string sw_tcOutput_SplitArtist {
            get {
                return ResourceManager.GetString("sw_tcOutput_SplitArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload song info.
        /// </summary>
        public static string sw_tcOutput_UploadSongInfo {
            get {
                return ResourceManager.GetString("sw_tcOutput_UploadSongInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string sw_tcSpotify_SaveButton {
            get {
                return ResourceManager.GetString("sw_tcSpotify_SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liked Songs Playlist.
        /// </summary>
        public static string sw_tcSpotify_SongLikeLabel {
            get {
                return ResourceManager.GetString("sw_tcSpotify_SongLikeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The playlist that songs get added when using the !songlike command or with the option to automatically add songs to the playlist..
        /// </summary>
        public static string sw_tcSpotify_SongLikeLabelTooltip {
            get {
                return ResourceManager.GetString("sw_tcSpotify_SongLikeLabelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Own AppID.
        /// </summary>
        public static string sw_tcSpotify_UseOwnApp {
            get {
                return ResourceManager.GetString("sw_tcSpotify_UseOwnApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Songify AppID.
        /// </summary>
        public static string sw_tcSpotify_UseSongifyApp {
            get {
                return ResourceManager.GetString("sw_tcSpotify_UseSongifyApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autostart with windows.
        /// </summary>
        public static string sw_tcSystem_Autostart {
            get {
                return ResourceManager.GetString("sw_tcSystem_Autostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        public static string sw_tcSystem_Behavior {
            get {
                return ResourceManager.GetString("sw_tcSystem_Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHECK FOR UPDATES.
        /// </summary>
        public static string sw_tcSystem_CheckButton {
            get {
                return ResourceManager.GetString("sw_tcSystem_CheckButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chrome fetch rate (seconds).
        /// </summary>
        public static string sw_tcSystem_ChromeFetchRate {
            get {
                return ResourceManager.GetString("sw_tcSystem_ChromeFetchRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string sw_tcSystem_lblLanguage {
            get {
                return ResourceManager.GetString("sw_tcSystem_lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minimize to system tray.
        /// </summary>
        public static string sw_tcSystem_Minimize {
            get {
                return ResourceManager.GetString("sw_tcSystem_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send anonymous data.
        /// </summary>
        public static string sw_tcSystem_SendAnonData {
            get {
                return ResourceManager.GetString("sw_tcSystem_SendAnonData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telemetry.
        /// </summary>
        public static string sw_tcSystem_Telemetry {
            get {
                return ResourceManager.GetString("sw_tcSystem_Telemetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (translated using DeepL).
        /// </summary>
        public static string sw_tcSystem_translated {
            get {
                return ResourceManager.GetString("sw_tcSystem_translated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string sw_Twitch_LogOut {
            get {
                return ResourceManager.GetString("sw_Twitch_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Reward.
        /// </summary>
        public static string sw_Twitch_Rewards_CreateNewReward {
            get {
                return ResourceManager.GetString("sw_Twitch_Rewards_CreateNewReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically start the web server.
        /// </summary>
        public static string sw_WebServer_AutoStart {
            get {
                return ResourceManager.GetString("sw_WebServer_AutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Website.
        /// </summary>
        public static string sw_WebServer_OpenWebsite {
            get {
                return ResourceManager.GetString("sw_WebServer_OpenWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web server Port.
        /// </summary>
        public static string sw_WebServer_Port {
            get {
                return ResourceManager.GetString("sw_WebServer_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Web Server.
        /// </summary>
        public static string sw_WebServer_StartWebServer {
            get {
                return ResourceManager.GetString("sw_WebServer_StartWebServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Web Server.
        /// </summary>
        public static string sw_WebServer_StopWebServer {
            get {
                return ResourceManager.GetString("sw_WebServer_StopWebServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blacklist.
        /// </summary>
        public static string WinTitle_Blocklist {
            get {
                return ResourceManager.GetString("WinTitle_Blocklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot Responses &amp; Commands.
        /// </summary>
        public static string WinTitle_BotResponsesCommands {
            get {
                return ResourceManager.GetString("WinTitle_BotResponsesCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song History.
        /// </summary>
        public static string WinTitle_History {
            get {
                return ResourceManager.GetString("WinTitle_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Queue.
        /// </summary>
        public static string WinTitle_Queue {
            get {
                return ResourceManager.GetString("WinTitle_Queue", resourceCulture);
            }
        }
    }
}
