//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Songify_Slim.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Songify_Slim.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist is blocked.
        /// </summary>
        public static string brw_ArtistBlocked {
            get {
                return ResourceManager.GetString("brw_ArtistBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error fetching songdata.
        /// </summary>
        public static string brw_FetchError {
            get {
                return ResourceManager.GetString("brw_FetchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure the bot responses for the following scenarios:.
        /// </summary>
        public static string brw_Header {
            get {
                return ResourceManager.GetString("brw_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max songs in queue.
        /// </summary>
        public static string brw_MaxSongs {
            get {
                return ResourceManager.GetString("brw_MaxSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song already in queue.
        /// </summary>
        public static string brw_SongInQueue {
            get {
                return ResourceManager.GetString("brw_SongInQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song longer than X.
        /// </summary>
        public static string brw_SongTooLong {
            get {
                return ResourceManager.GetString("brw_SongTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song added successfully.
        /// </summary>
        public static string brw_Success {
            get {
                return ResourceManager.GetString("brw_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string bw_btnAdd {
            get {
                return ResourceManager.GetString("bw_btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string bw_btnClear {
            get {
                return ResourceManager.GetString("bw_btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string bw_cbArtist {
            get {
                return ResourceManager.GetString("bw_cbArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string bw_cbUser {
            get {
                return ResourceManager.GetString("bw_cbUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked Artists.
        /// </summary>
        public static string bw_lblBlockedArtists {
            get {
                return ResourceManager.GetString("bw_lblBlockedArtists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked Users.
        /// </summary>
        public static string bw_lblBlockedUsers {
            get {
                return ResourceManager.GetString("bw_lblBlockedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string bw_menu_Delete {
            get {
                return ResourceManager.GetString("bw_menu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string lang_deDE {
            get {
                return ResourceManager.GetString("lang_deDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string lang_en {
            get {
                return ResourceManager.GetString("lang_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blacklist.
        /// </summary>
        public static string mw_menu_Blacklist {
            get {
                return ResourceManager.GetString("mw_menu_Blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string mw_menu_Connect {
            get {
                return ResourceManager.GetString("mw_menu_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string mw_menu_Disconnect {
            get {
                return ResourceManager.GetString("mw_menu_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string mw_menu_Exit {
            get {
                return ResourceManager.GetString("mw_menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string mw_menu_File {
            get {
                return ResourceManager.GetString("mw_menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string mw_menu_Help {
            get {
                return ResourceManager.GetString("mw_menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string mw_menu_Help_About {
            get {
                return ResourceManager.GetString("mw_menu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string mw_menu_History {
            get {
                return ResourceManager.GetString("mw_menu_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History Window.
        /// </summary>
        public static string mw_menu_History_Window {
            get {
                return ResourceManager.GetString("mw_menu_History_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History Browser.
        /// </summary>
        public static string mw_menu_Histoy_Browser {
            get {
                return ResourceManager.GetString("mw_menu_Histoy_Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        public static string mw_menu_Queue {
            get {
                return ResourceManager.GetString("mw_menu_Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue Browser.
        /// </summary>
        public static string mw_menu_Queue_Browser {
            get {
                return ResourceManager.GetString("mw_menu_Queue_Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Queue.
        /// </summary>
        public static string mw_menu_Queue_Clear {
            get {
                return ResourceManager.GetString("mw_menu_Queue_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue Window.
        /// </summary>
        public static string mw_menu_Queue_Window {
            get {
                return ResourceManager.GetString("mw_menu_Queue_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string mw_menu_Settings {
            get {
                return ResourceManager.GetString("mw_menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string mw_menu_Support {
            get {
                return ResourceManager.GetString("mw_menu_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widget.
        /// </summary>
        public static string mw_menu_Widget {
            get {
                return ResourceManager.GetString("mw_menu_Widget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon songify {
            get {
                object obj = ResourceManager.GetObject("songify", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color:.
        /// </summary>
        public static string sw_Appearance_Color {
            get {
                return ResourceManager.GetString("sw_Appearance_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Theme.
        /// </summary>
        public static string sw_Appearance_ThemeDark {
            get {
                return ResourceManager.GetString("sw_Appearance_ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Theme.
        /// </summary>
        public static string sw_Appearance_ThemeLight {
            get {
                return ResourceManager.GetString("sw_Appearance_ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPORT CONFIG.
        /// </summary>
        public static string sw_Config_Export {
            get {
                return ResourceManager.GetString("sw_Config_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMPORT CONFIG.
        /// </summary>
        public static string sw_Config_Import {
            get {
                return ResourceManager.GetString("sw_Config_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autoconnect.
        /// </summary>
        public static string sw_Integration_Autoconnect {
            get {
                return ResourceManager.GetString("sw_Integration_Autoconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LINK.
        /// </summary>
        public static string sw_Integration_btnLink {
            get {
                return ResourceManager.GetString("sw_Integration_btnLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Bot Responses.
        /// </summary>
        public static string sw_Integration_ConfigureResponses {
            get {
                return ResourceManager.GetString("sw_Integration_ConfigureResponses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NB Username (Twitch Username).
        /// </summary>
        public static string sw_Integration_NBWatermark {
            get {
                return ResourceManager.GetString("sw_Integration_NBWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked account:.
        /// </summary>
        public static string sw_Integration_SpotifyLinked {
            get {
                return ResourceManager.GetString("sw_Integration_SpotifyLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel to join.
        /// </summary>
        public static string sw_Integration_TwitchChWatermark {
            get {
                return ResourceManager.GetString("sw_Integration_TwitchChWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Points Reward ID.
        /// </summary>
        public static string sw_SpotifySR_ChannelPoints {
            get {
                return ResourceManager.GetString("sw_SpotifySR_ChannelPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Queue on Startup.
        /// </summary>
        public static string sw_SpotifySR_ClearQ {
            get {
                return ResourceManager.GetString("sw_SpotifySR_ClearQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Cooldown (seconds).
        /// </summary>
        public static string sw_SpotifySR_CommandCD {
            get {
                return ResourceManager.GetString("sw_SpotifySR_CommandCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Requests per User.
        /// </summary>
        public static string sw_SpotifySR_MaxReq {
            get {
                return ResourceManager.GetString("sw_SpotifySR_MaxReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Message Logging.
        /// </summary>
        public static string sw_SpotifySR_MessageLogging {
            get {
                return ResourceManager.GetString("sw_SpotifySR_MessageLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable SR (Command (!ssr SpotifyURI)).
        /// </summary>
        public static string sw_SpotifySR_SRCommand {
            get {
                return ResourceManager.GetString("sw_SpotifySR_SRCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable SR (Channel Rewards).
        /// </summary>
        public static string sw_SpotifySR_SRReward {
            get {
                return ResourceManager.GetString("sw_SpotifySR_SRReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string sw_tc_Appearance {
            get {
                return ResourceManager.GetString("sw_tc_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        public static string sw_tc_Config {
            get {
                return ResourceManager.GetString("sw_tc_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration.
        /// </summary>
        public static string sw_tc_Integration {
            get {
                return ResourceManager.GetString("sw_tc_Integration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string sw_tc_Output {
            get {
                return ResourceManager.GetString("sw_tc_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string sw_tc_System {
            get {
                return ResourceManager.GetString("sw_tc_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to append spaces.
        /// </summary>
        public static string sw_tcOutput_AddSpaces {
            get {
                return ResourceManager.GetString("sw_tcOutput_AddSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Directory.
        /// </summary>
        public static string sw_tcOutput_Directory {
            get {
                return ResourceManager.GetString("sw_tcOutput_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download album cover (only works with API).
        /// </summary>
        public static string sw_tcOutput_DownloadAlbum {
            get {
                return ResourceManager.GetString("sw_tcOutput_DownloadAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Format.
        /// </summary>
        public static string sw_tcOutput_Fromat {
            get {
                return ResourceManager.GetString("sw_tcOutput_Fromat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Text.
        /// </summary>
        public static string sw_tcOutput_PauseText {
            get {
                return ResourceManager.GetString("sw_tcOutput_PauseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom pause text (blank for emtpy text file).
        /// </summary>
        public static string sw_tcOutput_PauseWatermark {
            get {
                return ResourceManager.GetString("sw_tcOutput_PauseWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Artist and Title.
        /// </summary>
        public static string sw_tcOutput_SplitArtist {
            get {
                return ResourceManager.GetString("sw_tcOutput_SplitArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload song info.
        /// </summary>
        public static string sw_tcOutput_UploadSongInfo {
            get {
                return ResourceManager.GetString("sw_tcOutput_UploadSongInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autostart with windows.
        /// </summary>
        public static string sw_tcSystem_Autostart {
            get {
                return ResourceManager.GetString("sw_tcSystem_Autostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        public static string sw_tcSystem_Behavior {
            get {
                return ResourceManager.GetString("sw_tcSystem_Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHECK FOR UPDATES.
        /// </summary>
        public static string sw_tcSystem_CheckButton {
            get {
                return ResourceManager.GetString("sw_tcSystem_CheckButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chrome fetch rate (seconds).
        /// </summary>
        public static string sw_tcSystem_ChromeFetchRate {
            get {
                return ResourceManager.GetString("sw_tcSystem_ChromeFetchRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langauge.
        /// </summary>
        public static string sw_tcSystem_lblLangauge {
            get {
                return ResourceManager.GetString("sw_tcSystem_lblLangauge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minimize to system tray.
        /// </summary>
        public static string sw_tcSystem_Minimize {
            get {
                return ResourceManager.GetString("sw_tcSystem_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send anonymous data.
        /// </summary>
        public static string sw_tcSystem_SendAnonData {
            get {
                return ResourceManager.GetString("sw_tcSystem_SendAnonData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telemetry.
        /// </summary>
        public static string sw_tcSystem_Telemetry {
            get {
                return ResourceManager.GetString("sw_tcSystem_Telemetry", resourceCulture);
            }
        }
    }
}
