//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Songify_Slim.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Songify_Slim.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        public static string bw_btnAdd {
            get {
                return ResourceManager.GetString("bw_btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear ähnelt.
        /// </summary>
        public static string bw_btnClear {
            get {
                return ResourceManager.GetString("bw_btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Artist ähnelt.
        /// </summary>
        public static string bw_cbArtist {
            get {
                return ResourceManager.GetString("bw_cbArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User ähnelt.
        /// </summary>
        public static string bw_cbUser {
            get {
                return ResourceManager.GetString("bw_cbUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blocked Artists ähnelt.
        /// </summary>
        public static string bw_lblBlockedArtists {
            get {
                return ResourceManager.GetString("bw_lblBlockedArtists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blocked Users ähnelt.
        /// </summary>
        public static string bw_lblBlockedUsers {
            get {
                return ResourceManager.GetString("bw_lblBlockedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string bw_menu_Delete {
            get {
                return ResourceManager.GetString("bw_menu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die German ähnelt.
        /// </summary>
        public static string lang_deDE {
            get {
                return ResourceManager.GetString("lang_deDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die English ähnelt.
        /// </summary>
        public static string lang_en {
            get {
                return ResourceManager.GetString("lang_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blacklist ähnelt.
        /// </summary>
        public static string mw_menu_Blacklist {
            get {
                return ResourceManager.GetString("mw_menu_Blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connect ähnelt.
        /// </summary>
        public static string mw_menu_Connect {
            get {
                return ResourceManager.GetString("mw_menu_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disconnect ähnelt.
        /// </summary>
        public static string mw_menu_Disconnect {
            get {
                return ResourceManager.GetString("mw_menu_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
        /// </summary>
        public static string mw_menu_Exit {
            get {
                return ResourceManager.GetString("mw_menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        public static string mw_menu_File {
            get {
                return ResourceManager.GetString("mw_menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        /// </summary>
        public static string mw_menu_Help {
            get {
                return ResourceManager.GetString("mw_menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        public static string mw_menu_Help_About {
            get {
                return ResourceManager.GetString("mw_menu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die History ähnelt.
        /// </summary>
        public static string mw_menu_History {
            get {
                return ResourceManager.GetString("mw_menu_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die History Window ähnelt.
        /// </summary>
        public static string mw_menu_History_Window {
            get {
                return ResourceManager.GetString("mw_menu_History_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die History Browser ähnelt.
        /// </summary>
        public static string mw_menu_Histoy_Browser {
            get {
                return ResourceManager.GetString("mw_menu_Histoy_Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Queue ähnelt.
        /// </summary>
        public static string mw_menu_Queue {
            get {
                return ResourceManager.GetString("mw_menu_Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Queue Browser ähnelt.
        /// </summary>
        public static string mw_menu_Queue_Browser {
            get {
                return ResourceManager.GetString("mw_menu_Queue_Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear Queue ähnelt.
        /// </summary>
        public static string mw_menu_Queue_Clear {
            get {
                return ResourceManager.GetString("mw_menu_Queue_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Queue Window ähnelt.
        /// </summary>
        public static string mw_menu_Queue_Window {
            get {
                return ResourceManager.GetString("mw_menu_Queue_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string mw_menu_Settings {
            get {
                return ResourceManager.GetString("mw_menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Support ähnelt.
        /// </summary>
        public static string mw_menu_Support {
            get {
                return ResourceManager.GetString("mw_menu_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Widget ähnelt.
        /// </summary>
        public static string mw_menu_Widget {
            get {
                return ResourceManager.GetString("mw_menu_Widget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        public static System.Drawing.Icon songify {
            get {
                object obj = ResourceManager.GetObject("songify", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color: ähnelt.
        /// </summary>
        public static string sw_Appearance_Color {
            get {
                return ResourceManager.GetString("sw_Appearance_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dark Theme ähnelt.
        /// </summary>
        public static string sw_Appearance_ThemeDark {
            get {
                return ResourceManager.GetString("sw_Appearance_ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Light Theme ähnelt.
        /// </summary>
        public static string sw_Appearance_ThemeLight {
            get {
                return ResourceManager.GetString("sw_Appearance_ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EXPORT CONFIG ähnelt.
        /// </summary>
        public static string sw_Config_Export {
            get {
                return ResourceManager.GetString("sw_Config_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IMPORT CONFIG ähnelt.
        /// </summary>
        public static string sw_Config_Import {
            get {
                return ResourceManager.GetString("sw_Config_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die autoconnect ähnelt.
        /// </summary>
        public static string sw_Integration_Autoconnect {
            get {
                return ResourceManager.GetString("sw_Integration_Autoconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LINK ähnelt.
        /// </summary>
        public static string sw_Integration_btnLink {
            get {
                return ResourceManager.GetString("sw_Integration_btnLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NB Username (Twitch Username) ähnelt.
        /// </summary>
        public static string sw_Integration_NBWatermark {
            get {
                return ResourceManager.GetString("sw_Integration_NBWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Linked account: ähnelt.
        /// </summary>
        public static string sw_Integration_SpotifyLinked {
            get {
                return ResourceManager.GetString("sw_Integration_SpotifyLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Channel to join ähnelt.
        /// </summary>
        public static string sw_Integration_TwitchChWatermark {
            get {
                return ResourceManager.GetString("sw_Integration_TwitchChWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Channel Points Reward ID ähnelt.
        /// </summary>
        public static string sw_SpotifySR_ChannelPoints {
            get {
                return ResourceManager.GetString("sw_SpotifySR_ChannelPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear Queue on Startup ähnelt.
        /// </summary>
        public static string sw_SpotifySR_ClearQ {
            get {
                return ResourceManager.GetString("sw_SpotifySR_ClearQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Command Cooldown (seconds) ähnelt.
        /// </summary>
        public static string sw_SpotifySR_CommandCD {
            get {
                return ResourceManager.GetString("sw_SpotifySR_CommandCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max Requests per User ähnelt.
        /// </summary>
        public static string sw_SpotifySR_MaxReq {
            get {
                return ResourceManager.GetString("sw_SpotifySR_MaxReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable Message Logging ähnelt.
        /// </summary>
        public static string sw_SpotifySR_MessageLogging {
            get {
                return ResourceManager.GetString("sw_SpotifySR_MessageLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable SR (Command (!ssr SpotifyURI)) ähnelt.
        /// </summary>
        public static string sw_SpotifySR_SRCommand {
            get {
                return ResourceManager.GetString("sw_SpotifySR_SRCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable SR (Channel Rewards) ähnelt.
        /// </summary>
        public static string sw_SpotifySR_SRReward {
            get {
                return ResourceManager.GetString("sw_SpotifySR_SRReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Appearance ähnelt.
        /// </summary>
        public static string sw_tc_Appearance {
            get {
                return ResourceManager.GetString("sw_tc_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Config ähnelt.
        /// </summary>
        public static string sw_tc_Config {
            get {
                return ResourceManager.GetString("sw_tc_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Integration ähnelt.
        /// </summary>
        public static string sw_tc_Integration {
            get {
                return ResourceManager.GetString("sw_tc_Integration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Output ähnelt.
        /// </summary>
        public static string sw_tc_Output {
            get {
                return ResourceManager.GetString("sw_tc_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System ähnelt.
        /// </summary>
        public static string sw_tc_System {
            get {
                return ResourceManager.GetString("sw_tc_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Output Directory ähnelt.
        /// </summary>
        public static string sw_tcOutput_Directory {
            get {
                return ResourceManager.GetString("sw_tcOutput_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download album cover (only works with API) ähnelt.
        /// </summary>
        public static string sw_tcOutput_DownloadAlbum {
            get {
                return ResourceManager.GetString("sw_tcOutput_DownloadAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Output Format ähnelt.
        /// </summary>
        public static string sw_tcOutput_Fromat {
            get {
                return ResourceManager.GetString("sw_tcOutput_Fromat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pause Text ähnelt.
        /// </summary>
        public static string sw_tcOutput_PauseText {
            get {
                return ResourceManager.GetString("sw_tcOutput_PauseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Custom pause text (blank for emtpy text file) ähnelt.
        /// </summary>
        public static string sw_tcOutput_PauseWatermark {
            get {
                return ResourceManager.GetString("sw_tcOutput_PauseWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Split Artist and Title ähnelt.
        /// </summary>
        public static string sw_tcOutput_SplitArtist {
            get {
                return ResourceManager.GetString("sw_tcOutput_SplitArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Upload song info ähnelt.
        /// </summary>
        public static string sw_tcOutput_UploadSongInfo {
            get {
                return ResourceManager.GetString("sw_tcOutput_UploadSongInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die autostart with windows ähnelt.
        /// </summary>
        public static string sw_tcSystem_Autostart {
            get {
                return ResourceManager.GetString("sw_tcSystem_Autostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Behavior ähnelt.
        /// </summary>
        public static string sw_tcSystem_Behavior {
            get {
                return ResourceManager.GetString("sw_tcSystem_Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CHECK FOR UPDATES ähnelt.
        /// </summary>
        public static string sw_tcSystem_CheckButton {
            get {
                return ResourceManager.GetString("sw_tcSystem_CheckButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chrome fetch rate (seconds) ähnelt.
        /// </summary>
        public static string sw_tcSystem_ChromeFetchRate {
            get {
                return ResourceManager.GetString("sw_tcSystem_ChromeFetchRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Langauge ähnelt.
        /// </summary>
        public static string sw_tcSystem_lblLangauge {
            get {
                return ResourceManager.GetString("sw_tcSystem_lblLangauge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die minimize to system tray ähnelt.
        /// </summary>
        public static string sw_tcSystem_Minimize {
            get {
                return ResourceManager.GetString("sw_tcSystem_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die send anonymous data ähnelt.
        /// </summary>
        public static string sw_tcSystem_SendAnonData {
            get {
                return ResourceManager.GetString("sw_tcSystem_SendAnonData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Telemetry ähnelt.
        /// </summary>
        public static string sw_tcSystem_Telemetry {
            get {
                return ResourceManager.GetString("sw_tcSystem_Telemetry", resourceCulture);
            }
        }
    }
}
